[google_oauth]
client_id = "95430262855-t27t7gpelsk87sssud9c053d683c4sni.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://cap-kt-kutai-barat.streamlit.app"



